version: '3.8'

services:
  snapnewsil:
    # תחליף את yourusername בשם המשתמש שלך ב-Docker Hub שאליו דחפת את ה-image קודם
    image: talevi83/snapnewsil:latest
    container_name: snapnews
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - OPENAI_API_KEY=<openAI key>
      # https://newsapi.org/ -> Get API Key
      - NEWS_API_KEY=<newsAPI key>
    restart: unless-stopped
